#!/usr/bin/env bash
set -euo pipefail

CONFIG_FILE="config.env"
SAMPLE_FILE="config.env.sample"

prompt_default() {
  local prompt="$1"
  local default="$2"
  local value
  read -r -p "$prompt [$default]: " value
  printf '%s' "${value:-$default}"
}

prompt_yes_no() {
  local prompt="$1"
  local default="$2"
  local value
  local suffix
  if [ "$default" = "yes" ]; then
    suffix="Y/n"
  else
    suffix="y/N"
  fi

  while true; do
    read -r -p "$prompt [$suffix]: " value
    value="${value:-$default}"
    case "$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')" in
      y|yes) return 0 ;;
      n|no) return 1 ;;
      *) echo "Please answer yes or no." ;;
    esac
  done
}

random_hex() {
  openssl rand -hex "${1:-32}" 2>/dev/null || {
    echo "Error: openssl is required to generate secrets" >&2
    exit 1
  }
}

credential_key() {
  openssl rand -base64 32 | tr '+/' '-_'
}

write_config() {
  local key="$1"
  local value="$2"
  printf '%s=%s\n' "$key" "$value" >> "$CONFIG_FILE"
}

host_rule() {
  local host="$1"
  local path_rule="$2"
  if [ "$host" = "localhost" ] || [ -z "$host" ]; then
    printf '%s' "$path_rule"
  else
    printf 'Host(`%s`) && (%s)' "$host" "$path_rule"
  fi
}

append_profile() {
  local profile="$1"
  if [ -z "$compose_profiles" ]; then
    compose_profiles="$profile"
  else
    compose_profiles="$compose_profiles,$profile"
  fi
}

if [ ! -f "$SAMPLE_FILE" ]; then
  echo "Error: $SAMPLE_FILE not found. Run this script from the self-host bundle directory." >&2
  exit 1
fi

if [ -f "$CONFIG_FILE" ]; then
  if ! prompt_yes_no "$CONFIG_FILE already exists. Overwrite it" "no"; then
    echo "Keeping existing $CONFIG_FILE"
    exit 0
  fi
fi

echo "BreakTest self-host installer"
echo

version=$(prompt_default "BreakTest image version" "latest")
registry=$(prompt_default "Docker image registry/namespace" "breakingit")
compose_project_name=$(prompt_default "Docker Compose project name" "breaktest")
hostname=$(prompt_default "Hostname users will use to access BreakTest" "localhost")
license_key=$(prompt_default "BreakTest license key (can be left empty and added later)" "")

if prompt_yes_no "Enable HTTPS with Let's Encrypt" "no"; then
  enable_ssl="true"
  entrypoints="websecure"
  tls="true"
  cert_resolver="letsencrypt"
  email=$(prompt_default "Let's Encrypt email" "admin@example.com")
else
  enable_ssl="false"
  entrypoints="web"
  tls="false"
  cert_resolver="letsencrypt"
  email="admin@example.com"
fi

if prompt_yes_no "Start a local load generator in this stack" "yes"; then
  compose_profiles=""
  append_profile "loadgenerator"
  lg_location=$(prompt_default "Local load generator location label" "Local")
  lg_public="false"
  if prompt_yes_no "Make this local load generator public to all customers" "yes"; then
    lg_public="true"
  fi
  lg_customer_name=$(prompt_default "Local load generator customer name" "Default")
  lg_supports_sm="false"
  if prompt_yes_no "Allow this local load generator to run synthetic monitoring" "yes"; then
    lg_supports_sm="true"
  fi
else
  compose_profiles=""
  lg_location="Local"
  lg_public="true"
  lg_customer_name="Default"
  lg_supports_sm="false"
fi

ai_assistant_enabled="false"
anthropic_api_key=""
openai_access_token=""
openai_refresh_token=""
openai_token_expires=""
openai_email=""
ai_model=""
if prompt_yes_no "Configure AI assistant provider now" "no"; then
  if prompt_yes_no "Use Anthropic API key" "yes"; then
    anthropic_api_key=$(prompt_default "Anthropic API key" "")
  else
    openai_access_token=$(prompt_default "OpenAI access token" "")
    openai_refresh_token=$(prompt_default "OpenAI refresh token" "")
    openai_token_expires=$(prompt_default "OpenAI token expiry (optional)" "")
    openai_email=$(prompt_default "OpenAI account email (optional)" "")
  fi
  ai_model=$(prompt_default "AI model override (optional)" "")
fi
if [ -n "$anthropic_api_key" ] || { [ -n "$openai_access_token" ] && [ -n "$openai_refresh_token" ]; }; then
  ai_assistant_enabled="true"
  append_profile "ai-assistant"
fi
hermes_api_key=$(random_hex 32)

http_port=$(prompt_default "HTTP port" "80")
https_port=$(prompt_default "HTTPS port" "443")
timezone=$(prompt_default "Timezone" "Europe/Amsterdam")

frontend_rule=$(host_rule "$hostname" 'PathPrefix(`/`)')
backend_rule=$(host_rule "$hostname" 'PathPrefix(`/api`)')
websocket_rule=$(host_rule "$hostname" 'PathPrefix(`/ws`)')
pg_proxy_rule=$(host_rule "$hostname" 'PathPrefix(`/ingest`) || PathPrefix(`/upsert`)')

cat > "$CONFIG_FILE" <<EOF
# BreakTest self-host runtime configuration
# Generated by install.sh

BREAKTEST_VERSION=$version
BREAKTEST_IMAGE_REGISTRY=$registry
BREAKTEST_COMPOSE_PROJECT_NAME=$compose_project_name

CONTROLLER_HOST=$hostname
ENABLE_SSL=$enable_ssl
LETS_ENCRYPT_EMAIL=$email
HTTP_PORT=$http_port
HTTPS_PORT=$https_port
TRAEFIK_ENTRYPOINTS=$entrypoints
TRAEFIK_TLS=$tls
TRAEFIK_CERT_RESOLVER=$cert_resolver
TRAEFIK_FRONTEND_RULE='$frontend_rule'
TRAEFIK_BACKEND_RULE='$backend_rule'
TRAEFIK_WEBSOCKET_RULE='$websocket_rule'
TRAEFIK_PG_PROXY_RULE='$pg_proxy_rule'

TZ=$timezone
LOG_LEVEL=INFO
BACKUP_PATH=./backups

BREAKTEST_LICENSE_KEY=$license_key

AI_ASSISTANT_ENABLED=$ai_assistant_enabled
HERMES_URL=http://ai-assistant:8080
HERMES_API_KEY=$hermes_api_key
ANTHROPIC_API_KEY=$anthropic_api_key
OPENAI_ACCESS_TOKEN=$openai_access_token
OPENAI_REFRESH_TOKEN=$openai_refresh_token
OPENAI_TOKEN_EXPIRES=$openai_token_expires
OPENAI_EMAIL=$openai_email
AI_MODEL=$ai_model

JWT_SECRET_KEY=$(random_hex 32)
CREDENTIAL_ENCRYPTION_KEY=$(credential_key)
MONGO_INITDB_ROOT_USERNAME=admin
MONGO_INITDB_ROOT_PASSWORD=$(random_hex 24)
POSTGRES_USER=admin
POSTGRES_PASSWORD=$(random_hex 24)

MONGO_DATABASE=breakingit

POSTGRES_MAX_CONNECTIONS=100
POSTGRES_TIMEZONE=$timezone
POSTGRES_FSYNC=off
POSTGRES_SYNCHRONOUS_COMMIT=off
POSTGRES_FULL_PAGE_WRITES=on
POSTGRES_WORK_MEM=64MB

PG_PROXY_MAX_CONNS=100
PG_PROXY_MAX_INFLIGHT=512
PG_PROXY_COPY_TIMEOUT_SEC=60
PG_PROXY_MAX_BODY_BYTES=67108864

LOAD_GENERATOR_TOKEN=local-token
LOAD_GENERATOR_NAME=loadgenerator
LOAD_GENERATOR_LOCATION=$lg_location
LOAD_GENERATOR_RUN_MODE=process
LOAD_GENERATOR_PUBLIC=$lg_public
LOAD_GENERATOR_SUPPORTS_SYNTHETIC_MONITORING=$lg_supports_sm
LOAD_GENERATOR_CUSTOMER_NAME=$lg_customer_name
COMPOSE_PROFILES=$compose_profiles

AWS_ACCESS_KEY=
AWS_SECRET_KEY=
AWS_SES_REGION=eu-west-1
AZURE_SUBSCRIPTION_ID=
AZURE_TENANT_ID=
AZURE_CLIENT_ID=
AZURE_CLIENT_SECRET=
AZURE_SSH_PUBLIC_KEY=
AZURE_LOADGENERATOR_IMAGE=
AZURE_CONTAINER_REGISTRY_SERVER=
AZURE_CONTAINER_REGISTRY_USERNAME=
AZURE_CONTAINER_REGISTRY_PASSWORD=
AZURE_DOCKERHUB_USERNAME=
AZURE_DOCKERHUB_TOKEN=
DOP_API_TOKEN=
DOP_SSH_KEY_NAME=
GCP_PROJECT_ID=
GCP_SERVICE_ACCOUNT_KEY=
EOF

mkdir -p backups
case ",$compose_profiles," in
  *,loadgenerator,*) 
  mkdir -p loadgenerator/files
  ;;
esac

echo
echo "Created $CONFIG_FILE"
if [ -z "$license_key" ]; then
  echo "Add your BreakTest license key to BREAKTEST_LICENSE_KEY in config.env before starting tests."
fi
if [ "$enable_ssl" = "true" ]; then
  echo "Make sure DNS for $hostname points to this server and ports $http_port/$https_port are reachable."
fi
if [ "$ai_assistant_enabled" = "true" ]; then
  echo "AI assistant profile enabled. Backend access still requires a license with AI assistant enabled."
fi
echo "Start BreakTest with: ./start.sh"
