{
 "title": "System Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "breaktest_monitoring",
     "rawSql": "SELECT\n  time_bucket('$__interval'::interval, time) AS time,\n  instance_id,\n  avg(cpu_percent)\nFROM system_metrics\nWHERE $__timeFilter(time)\nGROUP BY 1,2\nORDER BY 1,2;"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "dataset": "breaktest_monitoring",
     "rawSql": "SELECT\n  time_bucket('$__interval'::interval, time) AS time,\n  instance_id,\n  avg(bytes_in_per_sec * 8)\nFROM system_metrics\nWHERE $__timeFilter(time)\nGROUP BY 1,2\nORDER BY 1,2;"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "breaktest_monitoring",
     "rawSql": "SELECT\n  time_bucket('$__interval'::interval, time) AS time,\n  instance_id,\n  avg(100 - memory_free_percent)\nFROM system_metrics\nWHERE $__timeFilter(time)\nGROUP BY 1,2\nORDER BY 1,2;"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "dataset": "breaktest_monitoring",
     "rawSql": "SELECT\n  time_bucket('$__interval'::interval, time) AS time,\n  instance_id,\n  avg(bytes_out_per_sec * 8)\nFROM system_metrics\nWHERE $__timeFilter(time)\nGROUP BY 1,2\nORDER BY 1,2;"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dataset": "breaktest_monitoring",
     "rawSql": "SELECT\n  time_bucket('$__interval'::interval, time) AS time,\n  instance_id,\n  avg(disk_free_bytes) as avg\nFROM system_metrics\nWHERE $__timeFilter(time)\nGROUP BY 1,2\nORDER BY 1,2;"
    }
   ]
  },
  {
   "title": "Total Network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "dataset": "breaktest_monitoring",
     "rawSql": "SELECT\n  time_bucket('$__interval'::interval, time) AS time,\n  sum(avg_bytes_in) as TotalIn\nFROM (\n  SELECT\n    time_bucket('$__interval'::interval, time) AS time,\n    instance_id,\n    avg(bytes_in_per_sec * 8) as avg_bytes_in\n  FROM system_metrics\n  WHERE $__timeFilter(time)\n  GROUP BY 1, 2\n) subq\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "dataset": "breaktest_monitoring",
     "rawSql": "SELECT\n  time_bucket('$__interval'::interval, time) AS time,\n  sum(avg_bytes_out) as out\nFROM (\n  SELECT\n    time_bucket('$__interval'::interval, time) AS time,\n    instance_id,\n    avg(bytes_out_per_sec * 8) as avg_bytes_out\n  FROM system_metrics\n  WHERE $__timeFilter(time)\n  GROUP BY 1, 2\n) subq\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "breaktest_monitoring",
     "rawSql": "SELECT\n  time_bucket('$__interval'::interval, time) AS time,\n  instance_id,\n  container_name,\n  avg(cpu_percent)\nFROM containers\nWHERE $__timeFilter(time) AND \n      container_name NOT LIKE '%agent%' AND container_name NOT LIKE '%jmeter-%' AND container_name NOT LIKE '%k6-%'\nGROUP BY 1,2,3\nORDER BY 1,2,3;"
    }
   ]
  },
  {
   "title": "Used Container Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dataset": "breaktest_monitoring",
     "rawSql": "SELECT\n  time_bucket('$__interval'::interval, time) AS time,\n  instance_id,\n  container_name,\n  avg(memory_usage_bytes)\nFROM containers\nWHERE $__timeFilter(time) AND\n      container_name NOT LIKE '%agent%' AND container_name NOT LIKE '%jmeter-%' AND container_name NOT LIKE '%k6-%'\nGROUP BY 1,2,3\nORDER BY 1,2,3;"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dataset": "breaktest_monitoring",
     "rawSql": "SELECT instance_id,\n       cpu_count as CPUs\nFROM (\n  SELECT DISTINCT ON (instance_id) instance_id, cpu_count\n  FROM system_metrics\n  WHERE time >= '${__to:date}'::timestamp - INTERVAL '1 minute'\n    AND time <= '${__to:date}'::timestamp\n  ORDER BY instance_id, time DESC\n) latest_cores;"
    },
    {
     "dataset": "breaktest_monitoring",
     "rawSql": "SELECT instance_id,\n       memory_total_mb* 1024 * 1024 as Memory\nFROM (\n  SELECT DISTINCT ON (instance_id) instance_id, memory_total_mb\n  FROM system_metrics\n  WHERE time >= '${__to:date}'::timestamp - INTERVAL '1 minute'\n    AND time <= '${__to:date}'::timestamp\n  ORDER BY instance_id, time DESC\n) latest_cores;"
    }
   ]
  },
  {
   "title": "Total Load generators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "breaktest_monitoring",
     "query": "memory_usage_bytes",
     "rawSql": "SELECT COUNT(DISTINCT instance_id) as load_generator_count\nFROM system_metrics\nWHERE $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Total Load generators CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "breaktest_monitoring",
     "rawSql": "SELECT SUM(cpu_count) as total_cpu_cores\nFROM (\n  SELECT DISTINCT ON (instance_id) instance_id, cpu_count\n  FROM system_metrics\n  WHERE time >= '${__to:date}'::timestamp - INTERVAL '1 minute'\n    AND time <= '${__to:date}'::timestamp\n  ORDER BY instance_id, time DESC\n) latest_cores;"
    }
   ]
  },
  {
   "title": "Total Load generators Mem",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "breaktest_monitoring",
     "rawSql": "SELECT SUM(memory_total_mb) * 1024 * 1024 as total_memory\nFROM (\n  SELECT DISTINCT ON (instance_id) instance_id, memory_total_mb\n  FROM system_metrics\n  WHERE time >= '${__to:date}'::timestamp - INTERVAL '1 minute'\n    AND time <= '${__to:date}'::timestamp\n  ORDER BY instance_id, time DESC\n) latest_cores;"
    }
   ]
  }
 ]
}